In [ ]:
# Install dependencies
%pip install -Uqq numpy ds_tut

import ds_tut
ds_tut.setup()

Note: you may need to restart the kernel to use updated packages.


# Numpy Tutorial

In [ ]:
import numpy as np

# Builtin Help

It's very easy to get additional help just from within a notebook.

## ? / help / ??

- Just append a `?` to an item to see the docstring or call `help(item)`
- Append `??` to view the source

In [ ]:
#np.array?

In [ ]:
#help(np.array)

In [ ]:
#np.abs??

## How to find Functions

In [ ]:
#np.lookfor('diagonal')

# Indices

In [ ]:
a = np.arange(9).reshape(3, 3)

In [ ]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a[1:,1:]

array([[4, 5],
       [7, 8]])

In [ ]:
a[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
a[a > 5] = 0
print(a)

[[0 1 2]
 [3 4 5]
 [0 0 0]]


In [ ]:
a.ravel()[::2] = 1
print(a)

[[1 1 1]
 [3 1 5]
 [1 0 1]]


# Broadcasting

In [ ]:
a = np.arange(9).reshape(3, 3)

In [ ]:
print(a * 10)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [ ]:
b = np.array((10, 10, 10))
print(b)

[10 10 10]


In [ ]:
print(a + b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print(a * b)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


# Non Scalar Multiplication

In [ ]:
(b @ b) ** .5

17.320508075688775

In [ ]:
a.dot(b), a @ b

(array([ 30, 120, 210]), array([ 30, 120, 210]))

In [ ]:
a @ np.arange(9).reshape(3, 3)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [ ]:
c = np.arange(4)

In [ ]:
#| notest
a @ c

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

# Elementwise Comparison

In [ ]:
a = np.full((2, 3), fill_value=2)

In [ ]:
b = np.full((2, 3), fill_value=2)

In [ ]:
a is b

False

In [ ]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.all(a == b)

True

In [ ]:
b[0, 0] = 1

In [ ]:
np.all(a == b)

False

# Performance

In [ ]:
n = 1000000

## Arrays vs Lists

In [ ]:
from math import sqrt
long_list = list(range(n))
%timeit [sqrt(_) for _ in long_list]

39.7 ms ± 668 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
long_array = np.arange(n)
%timeit np.sqrt(long_array)

## Loops are Bad

In [ ]:
x = 27

In [ ]:
#|notest
%%timeit 
count = 0
for i in range(1000000):
    if i % x == 0:
        count += 1

In [ ]:
a = np.arange(n)

In [ ]:
#|notest
%%timeit 
count = 0
for i in a:
    if i % x == 0:
        count += 1

In [ ]:
#|notest
%timeit np.sum(np.mod(a, x) == 0)