In [ ]:
import numpy as np

In [ ]:
Y = np.arange(25).reshape(5, 5).astype(np.float)

In [ ]:
y = Y.copy()

In [ ]:
index_array = np.array([2, 3, 2, 3, 2])

In [ ]:
for i in range(len(index_array)):
    index = index_array[i]
    mean_a = np.mean(y[i, :index])
    mean_b =  np.mean(y[i, index:])
    print(mean_a, mean_b)
    y[i, :index] -= mean_a
    y[i, index:] -= mean_b

0.5 3.0
6.0 8.5
10.5 13.0
16.0 18.5
20.5 23.0


In [ ]:
y[[0, 1], [2, 3]]

array([2., 8.])

In [ ]:
y[(1, 2, 3),(slice(1, 4), 2, 3)]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
rows = np.array([[0, 0], [3, 3]], dtype=np.intp)

In [ ]:
cols = np.array([[0, 2], [0, 2]], dtype=np.intp)

In [ ]:
y[rows, cols]

array([[ 0.,  2.],
       [15., 17.]])

In [ ]:
y[:,[1, 2]]

array([[ 1.,  2.],
       [ 6.,  7.],
       [11., 12.],
       [16., 17.],
       [21., 22.]])

In [ ]:
Y

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [ ]:
y[0, :2], y[0, 2:]

(array([0., 1.]), array([2., 3., 4.]))

In [ ]:
np.mean(y[0, :2]), np.mean(y[0, 2:]),

(0.5, 3.0)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [ ]:
y[[[0], [1]], [[2, 3]]]

array([[2., 3.],
       [7., 8.]])

# one dimensional

In [ ]:
Y = np.arange(25)

In [ ]:
y = Y.copy()

In [ ]:
y[[1, 2, 3], [4, 5, 6]]

IndexError: too many indices for array