# Numpy Tutorial

In [2]:
import numpy as np

# Eingebaute Hilfen

## ? / help

In [3]:
np.array?

In [44]:
#help(np.array)

## Funktionen finden

In [46]:
#np.lookfor('diagonal')

# Indizes

In [6]:
a = np.arange(9).reshape(3, 3)

In [7]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
a[1:,1:]

array([[4, 5],
       [7, 8]])

In [9]:
a[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [10]:
a[a > 5] = 0
print(a)

[[0 1 2]
 [3 4 5]
 [0 0 0]]


In [43]:
a.ravel()[::2] = 1
print(a)

[[1 1 1]
 [3 1 5]
 [1 7 1]]


# Broadcasting

In [11]:
a = np.arange(9).reshape(3, 3)

In [12]:
print(a * 10)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [33]:
b = np.array((10, 10, 10))
print(b)

[10 10 10]


In [15]:
print(a + b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [16]:
print(a * b)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


# Nicht skalare Multiplikation

In [39]:
(b @ b) ** .5

17.320508075688775

In [25]:
a.dot(b), a @ b

(array([ 30, 120, 210]), array([ 30, 120, 210]))

In [31]:
a @ np.arange(9).reshape(3, 3)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [26]:
c = np.arange(4)

In [27]:
a @ c

ValueError: shapes (3,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

# Elementweises Vergleichen

In [22]:
a = np.full((2, 3), fill_value=2)

In [24]:
b = np.full((2, 3), fill_value=2)

In [26]:
a is b

False

In [25]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [27]:
np.all(a == b)

True

In [28]:
b[0, 0] = 1

In [29]:
np.all(a == b)

False

# Performance

In [19]:
n = 1000000

## Arrays vs Listen

In [16]:
from math import sqrt
long_list = list(range(n))
%timeit [sqrt(_) for _ in long_list]

113 ms ± 1.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
long_array = np.arange(n)
%timeit np.sqrt(long_array)

2.3 ms ± 19.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Schleifen sind böse

In [34]:
x = 27

In [35]:
%%timeit 
count = 0
for i in range(1000000):
    if i % x == 0:
        count += 1

71.4 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
a = np.arange(n)

In [37]:
%%timeit 
count = 0
for i in a:
    if i % x == 0:
        count += 1

345 ms ± 1.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [41]:
%timeit np.sum(np.mod(a, x) == 0)

11.6 ms ± 93.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
