# Numpy Tutorial

In [ ]:
import numpy as np

# Eingebaute Hilfen

## ? / help

In [ ]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [ ]:
#help(np.array)

## Funktionen finden

In [ ]:
#np.lookfor('diagonal')

# Indizes

In [ ]:
a = np.arange(9).reshape(3, 3)

In [ ]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
a[1:,1:]

array([[4, 5],
       [7, 8]])

In [ ]:
a[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
a[a > 5] = 0
print(a)

[[0 1 2]
 [3 4 5]
 [0 0 0]]


In [ ]:
a.ravel()[::2] = 1
print(a)

[[1 1 1]
 [3 1 5]
 [1 0 1]]


# Broadcasting

In [ ]:
a = np.arange(9).reshape(3, 3)

In [ ]:
print(a * 10)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [ ]:
b = np.array((10, 10, 10))
print(b)

[10 10 10]


In [ ]:
print(a + b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print(a * b)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


# Nicht skalare Multiplikation

In [ ]:
(b @ b) ** .5

17.320508075688775

In [ ]:
a.dot(b), a @ b

(array([ 30, 120, 210]), array([ 30, 120, 210]))

In [ ]:
a @ np.arange(9).reshape(3, 3)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [ ]:
c = np.arange(4)

In [ ]:
a @ c

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

# Elementweises Vergleichen

In [ ]:
a = np.full((2, 3), fill_value=2)

In [ ]:
b = np.full((2, 3), fill_value=2)

In [ ]:
a is b

False

In [ ]:
a == b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
np.all(a == b)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
b[0, 0] = 1

In [ ]:
np.all(a == b)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

# Performance

In [ ]:
n = 1000000

## Arrays vs Listen

In [ ]:
from math import sqrt
long_list = list(range(n))
%timeit [sqrt(_) for _ in long_list]

83.7 ms ± 2.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
long_array = np.arange(n)
%timeit np.sqrt(long_array)

2.08 ms ± 175 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Schleifen sind böse

In [ ]:
x = 27

In [ ]:
%%timeit 
count = 0
for i in range(1000000):
    if i % x == 0:
        count += 1

45.7 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
a = np.arange(n)

In [ ]:
%%timeit 
count = 0
for i in a:
    if i % x == 0:
        count += 1

122 ms ± 3.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit np.sum(np.mod(a, x) == 0)

5.61 ms ± 127 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
